# Generated by Django 3.2 on 2021-04-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=5)),
                ('zipcode', models.CharField(max_length=10)),
                ('msacode', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('medianIncome', models.IntegerField(blank=True, default=None, null=True)),
                ('isNacaApproved', models.BinaryField(blank=True, default=False, editable=True, null=True)),
                ('geocode', models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
    ]
